// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIC9TB7qEnMbZp-eF0abxLsWsUqTFvLxY',
    appId: '1:924859557137:web:e1cf30d50277ba6aa998b0',
    messagingSenderId: '924859557137',
    projectId: 'app-mobil-e97a9',
    authDomain: 'app-mobil-e97a9.firebaseapp.com',
    storageBucket: 'app-mobil-e97a9.firebasestorage.app',
    measurementId: 'G-CDR2P4080K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqK1mcinnNlAu_1dnk0-7Kc0TYYfYn0gA',
    appId: '1:924859557137:android:00b6aceb5fa05998a998b0',
    messagingSenderId: '924859557137',
    projectId: 'app-mobil-e97a9',
    storageBucket: 'app-mobil-e97a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhEUjoNKSGmtk9ceHwXph8stBq4S8V29E',
    appId: '1:924859557137:ios:a9060e8ecf8cfaa3a998b0',
    messagingSenderId: '924859557137',
    projectId: 'app-mobil-e97a9',
    storageBucket: 'app-mobil-e97a9.firebasestorage.app',
    iosBundleId: 'com.example.lightMode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhEUjoNKSGmtk9ceHwXph8stBq4S8V29E',
    appId: '1:924859557137:ios:a9060e8ecf8cfaa3a998b0',
    messagingSenderId: '924859557137',
    projectId: 'app-mobil-e97a9',
    storageBucket: 'app-mobil-e97a9.firebasestorage.app',
    iosBundleId: 'com.example.lightMode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIC9TB7qEnMbZp-eF0abxLsWsUqTFvLxY',
    appId: '1:924859557137:web:2ed96a9417baa03aa998b0',
    messagingSenderId: '924859557137',
    projectId: 'app-mobil-e97a9',
    authDomain: 'app-mobil-e97a9.firebaseapp.com',
    storageBucket: 'app-mobil-e97a9.firebasestorage.app',
    measurementId: 'G-136EZ56SBX',
  );
}
